import React, { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Filter, ShieldCheck, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import Markdown from "react-markdown";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:5000";

const CRYPTO_COINS = [
  { id: "bitcoin", name: "Bitcoin", image: "/pred/bitcoin_analysis.png" },
  { id: "ethereum", name: "Ethereum", image: "/pred/ethereum_analysis.png" },
  { id: "ripple", name: "Ripple", image: "/pred/ripple_analysis.png" },
  { id: "cardano", name: "Cardano", image: "/pred/cardano_analysis.png" },
  { id: "solana", name: "Solana", image: "/pred/solana_analysis.png" },
];

const buildFallbackAnalysis = (coinName: string) => `### Key Trends & Observations
* Showing the saved CryptoSentinel analysis chart for **${coinName}**.
* Start the Flask backend to refresh this chart with live CoinGecko data and anomaly detection.

### Anomaly Breakdown
* Orange markers on the chart represent historical points flagged by the anomaly detector.
* Use these events as review points for sudden price or volume movement.

### Recommended Actions
* Compare anomaly dates with news, liquidity changes, and broader market conditions.
* Treat these signals as investigation prompts, not financial advice.

**This analysis is generated by CryptoSentinel's anomaly pipeline for educational purposes and is not financial advice. Do your own research.**`;

type ForecastComparisonRow = {
  model: string;
  type: string;
  rmse: number | null;
  mae: number | null;
  mape: number | null;
  status?: string;
};

type ForecastComparison = {
  best_model: string;
  comparison: ForecastComparisonRow[];
  test_points: number;
  advanced_tuned_params?: Record<string, number>;
};

const Dashboard = () => {
  const [selectedStock, setSelectedStock] = useState("bitcoin");
  const selectedCoin = useMemo(
    () => CRYPTO_COINS.find((coin) => coin.id === selectedStock) ?? CRYPTO_COINS[0],
    [selectedStock]
  );
  const [plotImage, setPlotImage] = useState(selectedCoin.image);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState(buildFallbackAnalysis(selectedCoin.name));
  const [anomalyCount, setAnomalyCount] = useState<number | null>(null);
  const [usingLiveData, setUsingLiveData] = useState(false);
  const [forecastComparison, setForecastComparison] = useState<ForecastComparison | null>(null);
  const [forecastLoading, setForecastLoading] = useState(false);
  const { toast } = useToast();

  const fetchStockData = async (stockCode: string) => {
    if (!stockCode) return;
    setLoading(true);
    setUsingLiveData(false);
    setPlotImage(selectedCoin.image);
    setAnalysis(buildFallbackAnalysis(selectedCoin.name));
    setAnomalyCount(null);

    try {
      const response = await fetch(`${API_BASE_URL}/api/analyze-crypto?stock_code=${stockCode}`);
      const data = await response.json();
      if (response.ok) {
        setPlotImage(`${API_BASE_URL}${data.image_path}`);
        setAnalysis(data.analysis);
        setAnomalyCount(data.anomaly_count ?? null);
        setUsingLiveData(true);
      } else {
        throw new Error(data.error ?? "Unable to fetch analysis");
      }
    } catch (error) {
      console.error("Error fetching data:", error);
      toast({
        title: "Using saved demo data",
        description: "Start the Flask backend for live anomaly analysis.",
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchForecastComparison = async (stockCode: string) => {
    if (!stockCode) return;
    setForecastLoading(true);

    try {
      const response = await fetch(`${API_BASE_URL}/api/forecast-comparison?stock_code=${stockCode}&days=90`);
      const data = await response.json();
      if (response.ok) {
        setForecastComparison(data);
      } else {
        throw new Error(data.error ?? "Unable to fetch forecast comparison");
      }
    } catch (error) {
      console.error("Error fetching forecast comparison:", error);
      setForecastComparison(null);
    } finally {
      setForecastLoading(false);
    }
  };

  useEffect(() => {
    fetchStockData(selectedStock);
    fetchForecastComparison(selectedStock);
  }, [selectedStock, selectedCoin.image, selectedCoin.name]);

  return (
    <DashboardLayout>
      <div className="p-6">
        {/* Overview section */}
        <div className="mb-8">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between mb-6">
            <div>
              <h2 className="text-2xl font-bold mb-1">
                CryptoSentinel Dashboard
              </h2>
              <p className="text-muted-foreground">
                AI-assisted anomaly detection for crypto market activity
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3">
              <div className="inline-flex items-center rounded-md border border-white/10 px-3 py-2 text-sm text-muted-foreground">
                <Activity className="mr-2 h-4 w-4 text-primary" />
                {usingLiveData ? "Live Flask analysis" : "Saved demo analysis"}
              </div>
              <Button size="sm" className="gap-2" onClick={() => fetchStockData(selectedStock)}>
                <Filter className="h-4 w-4" />
                <span>Refresh</span>
              </Button>
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-3 mb-8">
            <Card>
              <CardContent className="p-5 flex items-center gap-3">
                <ShieldCheck className="h-8 w-8 text-primary" />
                <div>
                  <p className="text-sm text-muted-foreground">Monitoring</p>
                  <p className="text-xl font-semibold">{selectedCoin.name}</p>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-5 flex items-center gap-3">
                <AlertTriangle className="h-8 w-8 text-warning" />
                <div>
                  <p className="text-sm text-muted-foreground">Anomalies</p>
                  <p className="text-xl font-semibold">{anomalyCount ?? "Demo"}</p>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-5 flex items-center gap-3">
                <TrendingUp className="h-8 w-8 text-success" />
                <div>
                  <p className="text-sm text-muted-foreground">Window</p>
                  <p className="text-xl font-semibold">30 days</p>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Main chart */}
          <div className="mb-8">
            <Tabs defaultValue="market" className="w-full">
              <div className="flex items-center justify-between mb-4">
                <TabsList className="bg-secondary">
                  <TabsTrigger value="market">Market Overview</TabsTrigger>
                </TabsList>

                <Select value={selectedStock} onValueChange={setSelectedStock}>
                  <SelectTrigger className="w-48 bg-secondary border-white/10">
                    <SelectValue placeholder="Select a token" />
                  </SelectTrigger>
                  <SelectContent>
                    {CRYPTO_COINS.map((coin) => (
                      <SelectItem key={coin.id} value={coin.id}>
                        {coin.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <TabsContent value="market" className="mt-0">
                <Card className="p-4">
                  <div className="relative min-h-[320px]">
                    {loading ? (
                      <div className="flex items-center justify-center h-[400px]">
                        <div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                      </div>
                    ) : (
                      plotImage ? (
                        <img
                          src={plotImage}
                          alt={`Analysis for ${selectedStock}`}
                          className="w-full h-auto object-contain"
                        />
                      ) : (
                        <div className="flex h-[320px] items-center justify-center text-muted-foreground">
                          No chart available
                        </div>
                      )
                    )}
                  </div>
                </Card>
              </TabsContent>
            </Tabs>
          </div>
        </div>
        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Anomaly Analysis</CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center p-8">
                <div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
              </div>
            ) : (
              <div className="space-y-3 leading-7 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:mt-4 [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mb-1 [&_strong]:font-semibold">
                <Markdown>{analysis}</Markdown>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="mb-8">
          <CardHeader>
            <CardTitle>Forecast Model Comparison</CardTitle>
          </CardHeader>
          <CardContent>
            {forecastLoading ? (
              <div className="flex items-center justify-center p-8">
                <div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" />
              </div>
            ) : forecastComparison ? (
              <div className="space-y-4">
                <div className="rounded-md border border-primary/20 bg-primary/10 p-4">
                  <p className="text-sm text-muted-foreground">Best model by RMSE</p>
                  <p className="text-lg font-semibold">{forecastComparison.best_model}</p>
                  <p className="text-sm text-muted-foreground">
                    Tested on {forecastComparison.test_points} chronological forecast points.
                  </p>
                  {forecastComparison.advanced_tuned_params && (
                    <p className="mt-2 text-xs text-muted-foreground">
                      Tuned params:{" "}
                      {Object.entries(forecastComparison.advanced_tuned_params)
                        .map(([key, value]) => `${key}=${value}`)
                        .join(", ")}
                    </p>
                  )}
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full min-w-[560px] text-sm">
                    <thead>
                      <tr className="border-b border-white/10 text-left text-muted-foreground">
                        <th className="py-3 pr-4 font-medium">Model</th>
                        <th className="py-3 pr-4 font-medium">Type</th>
                        <th className="py-3 pr-4 font-medium">RMSE</th>
                        <th className="py-3 pr-4 font-medium">MAE</th>
                        <th className="py-3 font-medium">MAPE</th>
                      </tr>
                    </thead>
                    <tbody>
                      {forecastComparison.comparison.map((row) => (
                        <tr key={row.model} className="border-b border-white/5">
                          <td className="py-3 pr-4 font-medium">{row.model}</td>
                          <td className="py-3 pr-4 text-muted-foreground">
                            {row.status ?? row.type}
                          </td>
                          <td className="py-3 pr-4">{row.rmse === null ? "N/A" : row.rmse.toFixed(2)}</td>
                          <td className="py-3 pr-4">{row.mae === null ? "N/A" : row.mae.toFixed(2)}</td>
                          <td className="py-3">{row.mape === null ? "N/A" : `${row.mape.toFixed(2)}%`}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ) : (
              <p className="text-muted-foreground">
                Start the Flask backend to load classical vs advanced forecast metrics.
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
};

export default Dashboard;
