import React from "react";
import { Activity, AlertTriangle, BarChart4, CheckCircle2, Database, Layers3 } from "lucide-react";

interface FeatureProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

const Feature: React.FC<FeatureProps> = ({ icon, title, description }) => (
  <div className="rounded-lg border border-white/10 bg-card/70 p-6">
    <div className="mb-4 inline-flex rounded-md border border-primary/20 bg-primary/10 p-3 text-primary">
      {icon}
    </div>
    <h3 className="text-lg font-semibold">{title}</h3>
    <p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p>
  </div>
);

export const Features = () => {
  const features = [
    {
      icon: <Database className="h-5 w-5" />,
      title: "CoinGecko data feed",
      description: "Pulls recent price and volume history for supported crypto assets through the Flask backend.",
    },
    {
      icon: <Layers3 className="h-5 w-5" />,
      title: "Feature engineering",
      description: "Builds return, volume-change, volatility, momentum, and rolling z-score features before scoring.",
    },
    {
      icon: <AlertTriangle className="h-5 w-5" />,
      title: "Event clustering",
      description: "Groups nearby suspicious points into reviewable events instead of flooding the dashboard.",
    },
    {
      icon: <Activity className="h-5 w-5" />,
      title: "Severity scoring",
      description: "Labels model outputs as Low, Medium, High, or Critical so the signal is easier to prioritize.",
    },
  ];

  return (
    <section className="py-20 relative">
      <div className="absolute inset-0 dot-pattern opacity-20 pointer-events-none" />

      <div className="container mx-auto px-6 relative z-10">
        <div className="max-w-3xl mb-12">
          <p className="text-sm font-medium uppercase tracking-wide text-primary">What is working now</p>
          <h2 className="mt-3 text-3xl font-bold md:text-4xl">
            A practical anomaly pipeline you can extend with your own model.
          </h2>
          <p className="mt-4 text-muted-foreground leading-7">
            The project is no longer just a static landing page. The dashboard
            can call Flask, refresh charts, and display model output in a format
            ready for a stronger custom detector.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
          {features.map((feature) => (
            <Feature key={feature.title} {...feature} />
          ))}
        </div>

        <div className="mt-16 grid grid-cols-1 gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
          <div>
            <p className="text-sm font-medium uppercase tracking-wide text-primary">Dashboard output</p>
            <h3 className="mt-3 text-2xl font-bold md:text-3xl">
              Real generated charts, not placeholder illustrations.
            </h3>
            <p className="mt-4 text-muted-foreground leading-7">
              The homepage now uses your generated analysis images directly.
              These are the same assets the dashboard can refresh when the
              backend is running.
            </p>

            <ul className="mt-6 space-y-3">
              {[
                "Chart images are loaded from public/pred",
                "Signals come from the anomaly pipeline in app.py",
                "The analysis panel is ready for your own model summary",
              ].map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <CheckCircle2 className="mt-0.5 h-5 w-5 flex-shrink-0 text-primary" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="rounded-lg border border-white/10 bg-card/70 p-3">
            <div className="mb-3 flex items-center justify-between px-2">
              <div>
                <p className="text-sm font-medium">Ethereum analysis</p>
                <p className="text-xs text-muted-foreground">Generated plot sample</p>
              </div>
              <BarChart4 className="h-5 w-5 text-primary" />
            </div>
            <img
              src="/pred/ethereum_analysis.png"
              alt="Ethereum anomaly analysis chart generated by CryptoSentinel"
              className="w-full rounded-md border border-white/10 object-cover"
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default Features;
