import React from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, BarChart3, ShieldAlert } from "lucide-react";
import { AnimatedButton } from "@/components/ui/AnimatedButton";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";

export const Hero = () => {
  const { isAuthenticated } = useAuth();
  const navigate = useNavigate();

  const openDashboard = () => {
    navigate(isAuthenticated ? "/dashboard" : "/signup");
  };

  return (
    <section className="relative min-h-[92vh] overflow-hidden flex items-center">
      <img
        src="/pred/bitcoin_analysis.png"
        alt="Bitcoin anomaly analysis chart generated by CryptoSentinel"
        className="absolute inset-0 h-full w-full object-cover opacity-35"
      />
      <div className="absolute inset-0 bg-gradient-to-r from-background via-background/90 to-background/40" />
      <div className="absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-background to-transparent" />

      <div className="container mx-auto px-6 relative z-10 pt-28 pb-20">
        <div className="max-w-4xl">
          <div className="inline-flex items-center gap-2 rounded-md border border-primary/25 bg-background/70 px-3 py-2 text-sm text-primary backdrop-blur">
            <ShieldAlert className="h-4 w-4" />
            Crypto anomaly detection from real market data
          </div>

          <h1 className="mt-7 max-w-3xl text-4xl font-bold leading-tight md:text-6xl lg:text-7xl">
            See unusual crypto moves before they become portfolio risk.
          </h1>

          <p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground md:text-xl">
            CryptoSentinel turns price and volume history into anomaly events,
            severity scores, and investigation notes for Bitcoin, Ethereum,
            Solana, Cardano, and Ripple.
          </p>

          <div className="mt-9 flex flex-col gap-3 sm:flex-row">
            <AnimatedButton size="lg" className="w-full sm:w-auto" onClick={openDashboard}>
              Open Dashboard <ArrowRight className="ml-2 h-4 w-4" />
            </AnimatedButton>
            <Button
              size="lg"
              variant="outline"
              className="w-full border-primary/20 bg-background/60 sm:w-auto"
              onClick={() => navigate("/features")}
            >
              How It Works
            </Button>
          </div>

          <div className="mt-12 grid max-w-3xl gap-3 sm:grid-cols-3">
            {[
              { label: "Signals", value: "Clustered events" },
              { label: "Model inputs", value: "Price + volume" },
              { label: "Output", value: "Severity scores" },
            ].map((stat) => (
              <div key={stat.label} className="rounded-lg border border-white/10 bg-background/70 p-4 backdrop-blur">
                <div className="flex items-center gap-2 text-primary">
                  <BarChart3 className="h-4 w-4" />
                  <span className="text-xs font-medium uppercase tracking-wide">{stat.label}</span>
                </div>
                <p className="mt-2 text-lg font-semibold">{stat.value}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
